### PR TITLE
Cleanup in preparation for v0.21

### PR DESCRIPTION
**Pull request by kelvinfan001**

### CODE REVIEW

**Comment by cgwalters** [comment]
(Only tangentially related, I wrote https://github.com/cgwalters/homegit/commit/284fa9bc47c18cd3b16893bbbc4e1dd3ee9c438b recently and find it useful for these "multi commit" PRs)

**Review by cgwalters — APPROVED** [review]
(Mostly superficial) LGTM

**Comment by kelvinfan001** [comment]
> (Only tangentially related, I wrote cgwalters/homegit@284fa9b recently and find it useful for these "multi commit" PRs)

Oh nice! Yeah I probably shouldn't have just left the PR comment blank, my apologies. Will copy the commit messages in the future :)

**Comment by bgilbert** [comment]
Followup in #98.

**Pull request merged**
