### PR TITLE
profile.sh: Update failed units' output

### LINKED ISSUE #81: Failed systemd units' names not showing in Fedora 33
On FCOS F33, after login, the names of the failed systemd units are not shown properly:
```
[core@cosa-devsh system]$ bash
[systemd]
Failed Units: 3
  ●
  ●
  ●
```

### PR DESCRIPTION
**Pull request by kelvinfan001**
Update to accommodate the new output format of `systemctl list-units`.
Fixes #81

### CODE REVIEW

**Review by cgwalters — APPROVED** [review]
Tentative approval but:
I don't quite understand the bug; if you have it handy could you paste the new output?

Is the problem that there's now a leading `●`?  But how did that break things?

**Comment by kelvinfan001** [comment]
@cgwalters Yep, the problem is with the new leading `●`. It broke things because we use `awk` to extract only the name of the failed unit from the output of `systemctl list-units`.
Originally, the output of `systemctl list-units` looked something like this:
```
$ systemctl list-units --state=failed --no-legend
fail-test-unit.service loaded failed failed Failing unit
```
Now it looks like this
```
$ systemctl list-units --state=failed --no-legend
● fail-test-unit.service loaded failed failed Failing unit
```
To address this, we could have simply changed [this line](https://github.com/coreos/console-login-helper-messages/blob/70b5ab7545062866684a37452dcdbd1c9202d369/usr/share/console-login-helper-messages/profile.sh#L15) to 
```
awk '{ print "  " $2 }' <<<"${FAILED}"
```
but I wanted to accommodate for older versions of `systemd` that had the output without the dot so I opted for the slightly more convoluted removal of the `●` (if it exists).

**Comment by jlebon** [comment]
There is a `--plain` which looks like it would help here:

```
--plain
    When used with list-dependencies, list-units or list-machines, the output is printed as a list
    instead of a tree, and the bullet circles are omitted.
```

(Ideally, we'd query the systemd API directly, though that's hacky to do via shell.)

**Comment by kelvinfan001** [comment]
@jlebon argh, I wish I noticed this option earlier. Using `--plain` would be much simpler. Thanks!

**Review by jlebon — APPROVED** [review]

**Pull request merged**
